// Package osmp: auto-generated glyph tables and ASD basis set.
//
// AUTO-GENERATED from sdk/python/osmp/protocol.py (dictionary v15)
//
// DO NOT EDIT — regenerate via: python3 tools/gen_asd.py
// Edits to this file will be silently overwritten on the next generation run.
//
// Patent pending — inventor Clay Holberg
// License: Apache 2.0
package osmp

// ASDFloorVersion is the guaranteed minimum vocabulary floor.
const ASDFloorVersion = "1.0"

// GlyphOperators — Category 1: Logical and Compositional Operators.
// Source: dictionary v15 Section 1, Category 1
var GlyphOperators = map[string]string{
	"∧": "AND", // U+2227 3B
	"∨": "OR", // U+2228 3B
	"¬": "NOT", // U+00AC 2B
	"→": "THEN", // U+2192 3B
	"↔": "IFF", // U+2194 3B
	"∀": "FOR-ALL", // U+2200 3B
	"∃": "EXISTS", // U+2203 3B
	"∥": "PARALLEL", // U+2225 3B
	">": "PRIORITY", // U+003E 1B
	"~": "APPROX", // U+007E 1B
	"*": "WILDCARD", // U+002A 1B
	":": "ASSIGN", // U+003A 1B
	";": "SEQUENCE", // U+003B 1B
	"?": "QUERY", // U+003F 1B
	"@": "TARGET", // U+0040 1B
	"⟳": "REPEAT-EVERY", // U+27F3 3B
	"≠": "NOT-EQUAL", // U+2260 3B
	"⊕": "PRIORITY-ORDER", // U+2295 3B
}

// ConsequenceClasses — Category 2: Consequence Class Designators.
// Required on every R: namespace instruction except ESTOP.
// HAZARDOUS and IRREVERSIBLE require I:§ human-in-the-loop precondition.
var ConsequenceClasses = map[string]string{
	"⚠": "HAZARDOUS", // U+26A0 hitl=true
	"↺": "REVERSIBLE", // U+21BA hitl=false
	"⊘": "IRREVERSIBLE", // U+2298 hitl=true
}

// LossPolicyGlyphs — Category 5: Loss Tolerance Policy Designators.
// Greek uppercase letters whose mathematical meanings map to policy semantics.
// Config: N:CFG@[nodeID]:FRAG[Φ|Γ|Λ]:τ[n]
var LossPolicyGlyphs = map[string]string{
	"Φ": "FAIL-SAFE", // U+03A6 2B legacy=FS
	"Γ": "GRACEFUL-DEGRADATION", // U+0393 2B legacy=GD
	"Λ": "ATOMIC", // U+039B 2B legacy=AT
}

// DictUpdateModeGlyphs — Category 6: Dictionary Update Mode Designators.
// REPLACE (←) requires mandatory FLAGS[C]: retransmit on loss, no graceful degradation.
var DictUpdateModeGlyphs = map[string]string{
	"+": "ADDITIVE", // U+002B 1B
	"←": "REPLACE", // U+2190 3B
	"†": "DEPRECATE", // U+2020 3B
}

// ASDFloorBasis is the compiled-in ASD basis set.
// Source: dictionary v15 (26 namespaces, 352 opcodes)
var ASDFloorBasis = map[string]map[string]string{
	"A": {
		"ACCEPT": "accept_proposed_action",
		"ACK": "positive_acknowledgment",
		"AR": "agentic_request",
		"ASD": "asd_version_identity_or_delta",
		"AUTH": "authorization_assertion",
		"CMP": "compress_compare",
		"CMPLY": "comply_with_proposed_action",
		"CMPR": "structured_comparison_returning_result",
		"COMP": "compliance_gate_assertion",
		"DA": "delegate_to_agent",
		"ERR": "error_handler",
		"MACRO": "registered_macro_invocation",
		"MDR": "mdr_corpus_version_identity_or_delta",
		"MEM": "memory_operation",
		"NACK": "negative_acknowledgment",
		"PERM": "permission_grant",
		"PING": "liveness_check",
		"PONG": "liveness_response",
		"PROPOSE": "propose_action_for_negotiation",
		"REJECT": "reject_proposed_action",
		"SUM": "summarize",
		"TRUST": "trust_assertion_about_agent_output",
		"TXN": "transaction_gate",
		"VERIFY": "request_output_verification",
	},
	"B": {
		"ALRM": "building_alarm",
		"AP": "access_point",
		"AREA": "building_sector_or_area",
		"HVAC": "hvac_system",
		"SAFE": "life_safety",
		"STRC": "structural",
	},
	"C": {
		"ALLOC": "resource_allocation",
		"CHKPT": "checkpoint_state",
		"FREE": "release_resource",
		"KILL": "terminate_process",
		"LIMIT": "resource_limit_enforcement",
		"MIGRT": "migrate_workload",
		"PAUSE": "pause_execution",
		"PRTY": "execution_priority",
		"QUOTA": "resource_quota",
		"RESUME": "resume_execution",
		"RSTRT": "restart",
		"SCALE": "scale_replicas",
		"SPAWN": "spawn_process_or_agent",
		"STAT": "resource_status",
	},
	"D": {
		"ABORT": "abort_transfer",
		"CHUNK": "file_chunk_payload",
		"CSUM": "checksum_verification",
		"FEED": "data_feed",
		"LOG": "log_entry",
		"PACK": "two_tier_corpus_encoding_for_at_rest_storage",
		"PULL": "request_payload_from_node",
		"PUSH": "push_payload_to_node",
		"Q": "query",
		"RESUME": "resume_interrupted_transfer",
		"RTN": "return_transmit",
		"STAT": "transfer_status_query",
		"UNPACK": "inference_free_semantic_retrieval_from_encoded_corpus",
		"XFER": "initiate_file_transfer",
	},
	"E": {
		"EQ": "environmental_query",
		"GPS": "gps_coordinates",
		"HAZ": "obstacle_or_hazard",
		"HU": "humidity",
		"PU": "pressure",
		"TH": "temperature_humidity_composite",
		"UV": "ultraviolet",
	},
	"F": {
		"AV": "authorization",
		"PRCD": "proceed_protocol",
		"QRY": "query_request",
		"WAIT": "wait_pause",
	},
	"G": {
		"BEARING": "heading_bearing",
		"CONF": "position_confidence_rating",
		"DOP": "dilution_of_precision",
		"DR": "dead_reckoning_state",
		"ELEV": "elevation_query",
		"POS": "position_coordinates",
		"RANGE": "distance_calculation",
		"ROUT": "routing_query",
		"TRAIL": "trail_segment_reference",
		"WPT": "waypoint_reference",
	},
	"H": {
		"ALERT": "threshold_crossing_event",
		"BP": "blood_pressure",
		"CASREP": "casualty_report",
		"CPT": "CPT_procedure_code_accessor",
		"ECG": "electrocardiogram",
		"GLUC": "glucose",
		"HR": "heart_rate",
		"ICD": "ICD-10_diagnosis_code_accessor",
		"MEDREC": "medical_record_log_entry",
		"RR": "respiratory_rate",
		"SNOMED": "SNOMED_CT_concept_identifier_accessor",
		"SPO2": "oxygen_saturation",
		"TEMP": "body_temperature",
		"TRIAGE": "triage_classification",
		"VITALS": "composite_vitals_status",
	},
	"I": {
		"AML": "anti_money_laundering_check",
		"BIO": "biometric_result",
		"CONS": "consent_and_scope_management",
		"ID": "identity_assertion",
		"KYC": "know_your_customer_check",
		"PERM": "permission_grant",
		"§": "human_operator_confirmation",
	},
	"J": {
		"ABANDON": "abandon_plan",
		"BELIEF": "assert_belief_state",
		"BLOCK": "blocked_on_dependency",
		"COMMIT": "commit_to_plan",
		"DECOMP": "task_decomposition",
		"DONE": "goal_achieved",
		"GOAL": "declare_goal",
		"HANDOFF": "transfer_execution_with_full_state_context",
		"INTENT": "assert_intention",
		"PLAN": "transmit_plan_state",
		"REPLAN": "trigger_replanning_from_current_state",
		"STATUS": "execution_status",
		"STEP": "current_plan_step",
		"SUBGOAL": "declare_subgoal",
	},
	"K": {
		"DIG": "digital_asset_operation",
		"ORD": "order_entry",
		"PAY": "payment_execution",
		"TRD": "trade_instruction",
		"XFR": "asset_transfer",
	},
	"L": {
		"ALERT": "compliance_alert",
		"ATTEST": "compliance_attestation",
		"AUDIT": "audit_log_entry",
		"CHAIN": "chain_of_custody",
		"EXPORT": "log_export",
		"FORENS": "forensic_capture",
		"LOG": "write_audit_record",
		"LSIGN": "log_signature",
		"PURGE": "log_purge",
		"QUERY": "audit_trail_query",
		"REPORT": "compliance_report",
		"RETAIN": "log_retention_policy",
		"SEV": "severity_level",
		"TRAIL": "audit_trail_query",
	},
	"M": {
		"ALRT": "municipal_alert_alarm",
		"EVA": "evacuation",
		"RTE": "route",
		"TYP": "incident_type",
	},
	"N": {
		"BK": "backup_node",
		"CFG": "configure",
		"CMD": "command_node",
		"INET": "internet_uplink_capability_query",
		"Q": "query_discovery",
		"RLY": "primary_relay",
		"STS": "status",
	},
	"O": {
		"BW": "available_bandwidth",
		"CHAN": "active_channel_type",
		"CONOPS": "concept_of_operations",
		"CONSTRAINT": "active_constraint_declaration",
		"DESC": "operational_deescalation",
		"EMCON": "emission_control_level",
		"ESCL": "operational_escalation",
		"FLOOR": "payload_floor_bytes",
		"IAP": "incident_action_plan",
		"LATENCY": "link_latency_class",
		"LINK": "link_quality",
		"LVL": "authority_level",
		"MESH": "mesh_topology_status",
		"MODE": "operational_mode",
		"PERIOD": "operational_period",
		"PHASE": "operational_phase",
		"POSTURE": "operational_posture",
		"READY": "readiness_condition",
		"SCOPE": "operational_scope",
		"TEMPO": "operational_tempo",
		"TYP": "incident_or_operation_type",
		"UPLINK": "uplink_availability",
	},
	"P": {
		"CODE": "maintenance_code_reference_for_compliance_logging",
		"DEVICE": "device_class_being_maintained",
		"GUIDE": "procedure_guide_reference",
		"PART": "part_reference",
		"STAT": "completion_status",
		"STEP": "step_index_within_guide",
	},
	"Q": {
		"ANL": "analysis_of_agent_output",
		"BENCH": "benchmark_assertion",
		"CITE": "cite_source_for_claim",
		"CONF": "confidence_interval_assertion",
		"CORRECT": "correction_directive",
		"CRIT": "structured_critique_of_agent_output",
		"EVAL": "evaluation_result",
		"FAIL": "quality_gate_fail",
		"FB": "feedback_on_agent_output",
		"FLAG": "flag_output_unreliable",
		"GROUND": "grounding_assertion_against_source_document",
		"HALLU": "hallucination_detection_flag",
		"JDG": "judgment_of_agent_output",
		"PASS": "quality_gate_pass",
		"REFLECT": "self_reflection_on_output_quality",
		"REVISE": "request_revision_based_on_critique",
		"RPRT": "structured_report_of_agent_output",
		"SCORE": "quality_score_assertion",
		"VERIFY": "request_verification_of_claim_by_another_agent",
	},
	"R": {
		"ACC": "accelerate_behavioral",
		"ACCEL": "accelerometer_data_stream",
		"BRK": "brake_actuator",
		"BT": "bluetooth_state",
		"CAM": "camera_activation",
		"COLLAB": "collaborative_mode",
		"DECEL": "decelerate_behavioral",
		"DISP": "display_brightness_or_state",
		"DPTH": "depth_control",
		"DRVE": "drive",
		"ESTOP": "emergency_stop",
		"FORM": "swarm_formation",
		"GPS": "gps_acquisition",
		"HANDOFF": "authority_handoff",
		"HAPTIC": "haptic_feedback_pattern",
		"HDNG": "heading",
		"LAND": "landing",
		"MIC": "microphone_activation",
		"MOV": "move",
		"NFC": "nfc_read_write",
		"NOTIF": "push_notification_to_device",
		"RTH": "return_to_home_origin",
		"SCRN": "screen_capture",
		"SPKR": "speaker_audio_output",
		"SRFC": "surface_command_UUV",
		"STAT": "status",
		"STOP": "stop",
		"THR": "throttle_actuator",
		"TKOF": "takeoff",
		"TORCH": "flashlight_on_off",
		"VIBE": "vibration_pattern",
		"WIFI": "wifi_state",
		"WPT": "waypoint",
		"ZONE": "safety_zone_declaration",
	},
	"S": {
		"ATST": "attest",
		"CERT": "certificate_operation",
		"DEC": "decrypt",
		"ENC": "encrypt",
		"HASH": "hash",
		"HMAC": "hmac",
		"KEYEX": "key_exchange",
		"KEYGEN": "key_generation",
		"OPEN": "open_sealed_payload",
		"REVOK": "revoke",
		"ROTATE": "key_rotation",
		"SEAL": "seal_payload",
		"SIGN": "sign",
		"TRUST": "trust_assertion",
		"VFY": "verify_signature",
	},
	"T": {
		"AFTER": "execute_after_condition",
		"ALARM": "time_alarm",
		"BEFORE": "execute_before_deadline",
		"CRON": "cron_expression",
		"DELAY": "delay_execution",
		"DUR": "duration_constraint",
		"EPOCH": "unix_epoch_reference",
		"EXP": "expiration",
		"NOW": "current_timestamp_query",
		"REPEAT": "recurring_schedule",
		"SCHED": "schedule_event",
		"SYNC": "time_synchronization",
		"UNTIL": "execute_until_condition",
		"WIN": "time_window",
	},
	"U": {
		"ACK": "human_acknowledgment",
		"ALERT": "urgent_operator_alert",
		"APPROVE": "request_human_approval",
		"ASSIGN": "assign_task_to_human_operator",
		"CONFIRM": "request_human_confirmation",
		"DELEGATE": "delegate_to_human",
		"DISPLAY": "display_information_to_operator",
		"ESCALATE": "escalate_to_human_decision_maker",
		"FEEDBACK": "request_human_feedback",
		"INPUT": "request_operator_input",
		"NOTIFY": "surface_message_to_operator",
		"OVERRIDE": "human_override_instruction",
		"REJECT": "human_rejection",
		"REVIEW": "request_human_review",
	},
	"V": {
		"AIS": "ais_position_report",
		"CARGO": "cargo_manifest",
		"COURSE": "course_over_ground",
		"DOCK": "docking_operation",
		"ETA": "estimated_time_arrival",
		"ETD": "estimated_time_departure",
		"FLEET": "fleet_coordination",
		"HDG": "heading",
		"MAYDAY": "distress_signal",
		"MMSI": "maritime_mobile_service_identity",
		"PANPAN": "urgency_signal",
		"PORT": "port_of_call",
		"POS": "vehicle_position",
		"ROUTE": "routing_instruction",
		"SPEED": "speed_over_ground",
		"STATUS": "vessel_status",
		"UNDOCK": "undocking_operation",
	},
	"W": {
		"ALERT": "weather_alert",
		"FCST": "forecast_product",
		"FIRE": "fire_weather_data",
		"FLOOD": "flood_data",
		"HURR": "hurricane_data",
		"METAR": "aviation_weather_observation",
		"PRECIP": "precipitation",
		"PRESS": "barometric_pressure",
		"TAF": "terminal_area_forecast",
		"TEMP": "ambient_temperature",
		"VIS": "visibility_report",
		"WARN": "weather_warning",
		"WATCH": "weather_watch",
		"WIND": "wind_speed_and_direction",
	},
	"X": {
		"CHG": "ev_charging_state",
		"DR": "demand_response_signal",
		"FAULT": "fault_event",
		"FREQ": "grid_frequency",
		"GRD": "grid_connection_status",
		"ISLND": "islanding_operation",
		"LOAD": "load_reading",
		"METER": "meter_reading",
		"PRICE": "energy_price_signal",
		"PROD": "generation_output",
		"RESTORE": "grid_restoration",
		"SHED": "load_shedding_instruction",
		"SOLAR": "solar_generation",
		"STORE": "storage_state",
		"VOLT": "voltage_level",
		"WND": "wind_generation",
	},
	"Y": {
		"CLEAR": "clear_memory_tier",
		"COMMIT": "commit_working_to_long_term_memory",
		"EMBED": "generate_embedding_for_storage",
		"FETCH": "retrieve_by_key",
		"FORGET": "delete_from_memory",
		"INDEX": "index_document_for_retrieval",
		"PAGEOUT": "page_out_working_memory_to_external_store",
		"RECALL": "retrieve_episodic_memory_by_context",
		"RETRIEVE": "retrieve_from_LCS",
		"SEARCH": "semantic_vector_search",
		"SHARE": "share_memory_segment_with_another_agent",
		"STORE": "store_to_memory",
		"SUMM": "summarize_and_compress_memory_segment",
		"SYNC": "synchronize_memory_state_with_peer",
		"USG": "report_memory_utilization",
	},
	"Z": {
		"BATCH": "batch_inference_request",
		"CACHE": "kv_cache_utilization_instruction",
		"CAPS": "capability_query",
		"CONF": "agent_reported_confidence",
		"COST": "inference_cost_report",
		"CTX": "context_window_utilization",
		"EMBED": "embedding_generation_request",
		"FINISH": "finish_reason",
		"INF": "invoke_inference",
		"LATENCY": "inference_latency_measurement",
		"MAXT": "max_tokens_parameter",
		"MDLUSED": "actual_model_used_in_inference_response",
		"MODEL": "specify_model_by_identifier",
		"RESP": "inference_response_payload_envelope",
		"ROUTE": "route_to_model_with_specified_capability",
		"STOP": "stop_sequence",
		"STREAM": "streaming_response_flag",
		"TEMP": "temperature_parameter",
		"TOKENS": "token_count_report",
		"TOPK": "top_k_sampling_parameter",
		"TOPP": "top_p_nucleus_sampling_parameter",
	},
}
